### ISSUE TITLE
I forked :)

### ISSUE THREAD

**Issue by pierreozoux** [codeformuenster/docker-compose-discourse#3]
As I saw it was not that maintained, I forked :)

https://github.com/indiehosters/discourse

Tell me if you want to collaborate to maintain the docker image/compose :)

**Comment by webwurst** [comment]
We just did this as a first test. Would be cool to collaborate on this :)

**Comment by pierreozoux** [comment]
My idea would be at the end of the day to lobby discourse team to make
it an official option to use this docker-compose thing.
(maybe as a fallback from their launcher)
And also to have an official docker image :)

What do you think to put it under an organisation like:
https://github.com/docker-discourse
(If you agree, then I put you admin there also)

Then I'll move my 2 repos under this organisation and we can work
together from this point.
(I prefer to have 2 repos:
- one for Dockerfile
- one for docker-compose.yml
  )

What do you think?

all the best!

On 08-01-2016 23:26, Tobias Bradtke wrote:

> We just did this as a first test. Would be cool to collaborate on this :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/codeformuenster/docker-compose-discourse/issues/3#issuecomment-170155406

## 

I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by webwurst** [comment]
I am totally fine with that.
Thanks!

**Comment by ubergesundheit** [comment]
yeah lets move the repositories to the organization.. 
Would be awesome to propose the docker-compose way as the official way to create a discourse instance

**Comment by pierreozoux** [comment]
@webwurst I just invited you, I let you decide who is appropriate to invite also.
I transfered ownership also.

Let continue the discussion with PRs :)
